#if UNITY_EDITOR
#pragma warning disable 618
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;

namespace DeepVain.Player.EditorTools
{
    /// <summary>
    /// Menu: DeepVain > Player Setup.
    /// Slices every layer sheet (pivot at the feet), makes one LayerSpriteSet per layer, one clip per animation
    /// (the clip only animates PlayerLayerSync.animId / frame), an Animator Controller and a Player prefab.
    /// </summary>
    public class PlayerSetupTool : EditorWindow
    {
        class AnimDef
        {
            public string name; public int w, ox, h = 40, pivotBottom = 1; public float speed = 1f; public int[] ms; public bool loop;
            public AnimDef(string n, int w, int ox, bool loop, params int[] ms) { name = n; this.w = w; this.ox = ox; this.loop = loop; this.ms = ms; }
        }

        // frame widths / x offsets / durations (ms) exactly as generated by the sprite script
        static readonly AnimDef[] Anims =
        {
            new AnimDef("Idle",   24, 0,  true,  160, 160, 160, 160, 160, 160),
            new AnimDef("Walk",   24, 0,  true,  100, 100, 100, 100, 100, 100, 100, 100),
            new AnimDef("Run",    24, 0,  true,  75, 75, 75, 75, 75, 75, 75, 75),
            new AnimDef("Jump",   24, 0,  false, 90, 90, 100),
            new AnimDef("Fall",   24, 0,  true,  90, 90),
            new AnimDef("Land",   24, 0,  false, 80, 90),
            new AnimDef("Climb",  24, 0,  true,  120, 120, 120, 120, 120, 120),
            new AnimDef("Attack", 32, 4,  false, 110, 70, 70, 90, 100, 110) { speed = 1.5f },
            new AnimDef("Hit",    24, 0,  false, 90, 100, 110),
            new AnimDef("Death",  44, 16, false, 90, 100, 110, 110, 120, 140, 300),
            new AnimDef("ShieldRaise", 24, 0, false, 80, 80, 90),
            new AnimDef("ShieldHold",  24, 0, true,  140, 140, 140, 140),
            new AnimDef("ShieldHit",   24, 0, false, 70, 80, 90, 100),
            new AnimDef("StunIntro",   32, 4, false, 80, 90, 100, 100) { h = 48 },
            new AnimDef("StunLoop",    32, 4, true,  100, 100, 100, 100, 100, 100, 100, 100) { h = 48 },
            new AnimDef("StunRecover", 32, 4, false, 100, 100, 110) { h = 48 },
            new AnimDef("PickUp",      32, 4, false, 90, 90, 130, 100, 100, 110),
            new AnimDef("ClimbIdle",   24, 0, true,  500, 500),
            new AnimDef("Chop",        32, 4, true,  90, 60, 50, 90, 80, 100),
            new AnimDef("Mine",        32, 4, true,  100, 70, 60, 100, 90, 110),
            new AnimDef("DeathFade",   44, 16, false, 90, 90, 90, 90, 90, 90, 90),
            // ledge: 56 x 80 frames, the pivot is on the ledge top where the player ends up standing (38 px above the bottom)
            new AnimDef("LedgeHang",   56, 30, true,  300, 300) { h = 80, pivotBottom = 38 },
            new AnimDef("LedgeClimb",  56, 30, false, 100, 90, 90, 100, 100, 90, 110) { h = 80, pivotBottom = 38 },
            // LedgeUp: the same climb drawn in place (pelvis fixed, pivot 16 px below it); LedgeClimbDriver moves the player
            new AnimDef("LedgeUp",     56, 30, false, 35, 35, 40, 40, 40, 40, 35, 35, 55, 55, 50, 50, 45, 45, 45, 45, 50, 50, 50, 50, 45, 45, 110) { h = 80, pivotBottom = 24 },
            // new: crouch, crouch walk, roll (drawn in place on a 40 x 40 canvas), drink, and the back view walk through doors
            new AnimDef("Crouch",      24, 0, true,  170, 170, 170, 170, 170, 170),
            new AnimDef("CrouchWalk",  24, 0, true,  110, 110, 110, 110, 110, 110, 110, 110),
            new AnimDef("Roll",        40, 8, false, 55, 50, 45, 45, 45, 45, 45, 45, 50, 60, 70),
            new AnimDef("Drink",       24, 0, false, 70, 70, 80, 110, 130, 110, 90, 80, 60),
            new AnimDef("EnterDoor",   24, 0, false, 90, 90, 90, 90, 90, 90, 90, 90),
        };

        // back to front
        static readonly string[] DrawOrder =
        {
            "ArmBack", "HandBack", "LegBack", "FootBack", "StarsBack", "HairBack_F", "Torso", "LegFront", "FootFront", "Head", "Face_M", "Face_F", "Hair_M", "Hair_F", "ArmFront", "HandFront", "StarsFront"
        };

        const int FrameH = 40;
        const float StandX = 12f;   // x of the feet centre inside the 24-wide frames

        string layersFolder = "Assets/PlayerV2/Layers";
        string outFolder = "Assets/PlayerV2/Generated";
        string shaderMaterial = "DeepVain/PlayerPaletteSwap";
        float ppu = 16f;

        [MenuItem("DeepVain/Player Setup")]
        static void Open() { GetWindow<PlayerSetupTool>("Player Setup"); }

        void OnGUI()
        {
            EditorGUILayout.HelpBox("1) Copy the PlayerV2 folder into Assets (Layers + Unity).\n2) Check the paths below.\n3) Press Build.", MessageType.Info);
            layersFolder = EditorGUILayout.TextField("Layers folder", layersFolder);
            outFolder = EditorGUILayout.TextField("Output folder", outFolder);
            ppu = EditorGUILayout.FloatField("Pixels Per Unit", ppu);
            EditorGUILayout.LabelField("Use the same Pixels Per Unit as your tiles / goblin so the sizes match.", EditorStyles.miniLabel);
            if (GUILayout.Button("Build", GUILayout.Height(32))) Build();
        }

        static void EnsureFolder(string path)
        {
            if (AssetDatabase.IsValidFolder(path)) return;
            string parent = Path.GetDirectoryName(path).Replace('\\', '/');
            EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, Path.GetFileName(path));
        }

        void Build()
        {
            EnsureFolder(outFolder);
            EnsureFolder(outFolder + "/LayerSets");
            EnsureFolder(outFolder + "/Clips");

            // 1) slice the sheets
            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (var layer in DrawOrder)
                    foreach (var a in Anims)
                    {
                        string path = $"{layersFolder}/{layer}/{layer}_{a.name}.png";
                        var imp = AssetImporter.GetAtPath(path) as TextureImporter;
                        if (imp == null) { Debug.LogWarning("Missing sheet: " + path); continue; }
                        imp.textureType = TextureImporterType.Sprite;
                        imp.spriteImportMode = SpriteImportMode.Multiple;
                        imp.spritePixelsPerUnit = ppu;
                        imp.filterMode = FilterMode.Point;
                        imp.textureCompression = TextureImporterCompression.Uncompressed;
                        imp.mipmapEnabled = false;
                        imp.alphaIsTransparency = true;
                        var metas = new SpriteMetaData[a.ms.Length];
                        for (int i = 0; i < metas.Length; i++)
                            metas[i] = new SpriteMetaData
                            {
                                name = $"{layer}_{a.name}_{i:00}",
                                rect = new Rect(i * a.w, 0, a.w, a.h),
                                alignment = (int)SpriteAlignment.Custom,
                                pivot = new Vector2((StandX + a.ox) / a.w, (float)a.pivotBottom / a.h)
                            };
                        imp.spritesheet = metas;
                        EditorUtility.SetDirty(imp);
                        imp.SaveAndReimport();
                    }
            }
            finally { AssetDatabase.StopAssetEditing(); }
            AssetDatabase.Refresh();

            // 2) one LayerSpriteSet per layer
            var sets = new Dictionary<string, LayerSpriteSet>();
            foreach (var layer in DrawOrder)
            {
                string setPath = $"{outFolder}/LayerSets/{layer}.asset";
                var set = AssetDatabase.LoadAssetAtPath<LayerSpriteSet>(setPath);
                if (set == null) { set = ScriptableObject.CreateInstance<LayerSpriteSet>(); AssetDatabase.CreateAsset(set, setPath); }
                set.animations = new List<LayerSpriteSet.AnimFrames>();
                foreach (var a in Anims)
                {
                    string path = $"{layersFolder}/{layer}/{layer}_{a.name}.png";
                    var sprites = AssetDatabase.LoadAllAssetsAtPath(path).OfType<Sprite>().OrderBy(s => s.name).ToArray();
                    set.animations.Add(new LayerSpriteSet.AnimFrames { anim = a.name, frames = sprites });
                }
                EditorUtility.SetDirty(set);
                sets[layer] = set;
            }

            // 3) one clip per animation: animId (constant) + frame (stepped)
            var clips = new Dictionary<string, AnimationClip>();
            for (int ai = 0; ai < Anims.Length; ai++)
            {
                var a = Anims[ai];
                string clipPath = $"{outFolder}/Clips/{a.name}.anim";
                AssetDatabase.DeleteAsset(clipPath);
                var clip = new AnimationClip { frameRate = 60f };
                var keys = new List<Keyframe>();
                float t = 0f;
                for (int i = 0; i < a.ms.Length; i++) { keys.Add(new Keyframe(t, i)); t += a.ms[i] / 1000f; }
                keys.Add(new Keyframe(t, a.ms.Length - 1));
                var frameCurve = new AnimationCurve(keys.ToArray());
                for (int k = 0; k < frameCurve.length; k++)
                {
                    AnimationUtility.SetKeyBroken(frameCurve, k, true);
                    AnimationUtility.SetKeyLeftTangentMode(frameCurve, k, AnimationUtility.TangentMode.Constant);
                    AnimationUtility.SetKeyRightTangentMode(frameCurve, k, AnimationUtility.TangentMode.Constant);
                }
                var idCurve = new AnimationCurve(new Keyframe(0f, ai), new Keyframe(t, ai));
                for (int k = 0; k < idCurve.length; k++)
                {
                    AnimationUtility.SetKeyBroken(idCurve, k, true);
                    AnimationUtility.SetKeyLeftTangentMode(idCurve, k, AnimationUtility.TangentMode.Constant);
                    AnimationUtility.SetKeyRightTangentMode(idCurve, k, AnimationUtility.TangentMode.Constant);
                }
                AnimationUtility.SetEditorCurve(clip, EditorCurveBinding.FloatCurve("", typeof(PlayerLayerSync), "frame"), frameCurve);
                AnimationUtility.SetEditorCurve(clip, EditorCurveBinding.FloatCurve("", typeof(PlayerLayerSync), "animId"), idCurve);
                var settings = AnimationUtility.GetAnimationClipSettings(clip);
                settings.loopTime = a.loop;
                AnimationUtility.SetAnimationClipSettings(clip, settings);
                AssetDatabase.CreateAsset(clip, clipPath);
                clips[a.name] = clip;
            }

            // 4) animator controller
            string ctrlPath = outFolder + "/Player.controller";
            AssetDatabase.DeleteAsset(ctrlPath);
            var ctrl = AnimatorController.CreateAnimatorControllerAtPath(ctrlPath);
            ctrl.AddParameter("Speed", AnimatorControllerParameterType.Float);
            ctrl.AddParameter("VelY", AnimatorControllerParameterType.Float);
            ctrl.AddParameter("Grounded", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Climbing", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Dead", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Jump", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Attack", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Hit", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Blocking", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Stunned", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("ClimbSpeed", AnimatorControllerParameterType.Float);
            ctrl.AddParameter("Stun", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("ShieldHit", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("PickUp", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Chopping", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Mining", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("LedgeHang", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("LedgeClimb", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Crouching", AnimatorControllerParameterType.Bool);
            ctrl.AddParameter("Roll", AnimatorControllerParameterType.Trigger);
            ctrl.AddParameter("Drink", AnimatorControllerParameterType.Trigger);
            var sm = ctrl.layers[0].stateMachine;
            var st = new Dictionary<string, AnimatorState>();
            foreach (var a in Anims) { var s = sm.AddState(a.name); s.motion = clips[a.name]; s.speed = a.speed; st[a.name] = s; }
            sm.defaultState = st["Idle"];

            AnimatorStateTransition Any(string to)
            {
                var tr = sm.AddAnyStateTransition(st[to]);
                tr.hasExitTime = false; tr.duration = 0f; tr.canTransitionToSelf = false; return tr;
            }
            AnimatorStateTransition Go(string from, string to, bool exit = false)
            {
                var tr = st[from].AddTransition(st[to]);
                tr.hasExitTime = exit; tr.exitTime = 1f; tr.duration = 0f; return tr;
            }
            var t1 = Any("Death"); t1.AddCondition(AnimatorConditionMode.If, 0, "Dead");
            var tSt = Any("StunIntro"); tSt.AddCondition(AnimatorConditionMode.If, 0, "Stun"); tSt.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead");
            var t2 = Any("Hit"); t2.AddCondition(AnimatorConditionMode.If, 0, "Hit"); t2.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); t2.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            var t3 = Any("Attack"); t3.AddCondition(AnimatorConditionMode.If, 0, "Attack"); t3.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); t3.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned"); t3.AddCondition(AnimatorConditionMode.IfNot, 0, "Blocking");
            var t4 = Any("Jump"); t4.AddCondition(AnimatorConditionMode.If, 0, "Jump"); t4.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); t4.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned"); t4.AddCondition(AnimatorConditionMode.IfNot, 0, "Blocking");
            var t5 = Any("Fall"); t5.AddCondition(AnimatorConditionMode.IfNot, 0, "Grounded"); t5.AddCondition(AnimatorConditionMode.Less, -0.1f, "VelY"); t5.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); t5.AddCondition(AnimatorConditionMode.IfNot, 0, "Climbing"); t5.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned"); t5.AddCondition(AnimatorConditionMode.IfNot, 0, "LedgeHang");
            var t7 = Any("PickUp"); t7.AddCondition(AnimatorConditionMode.If, 0, "PickUp"); t7.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); t7.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");

            // ladder: only entered from the normal states (so ClimbIdle does not get kicked back into Climb)
            foreach (var f in new[] { "Idle", "Walk", "Run", "Jump", "Fall", "Land" }) Go(f, "Climb").AddCondition(AnimatorConditionMode.If, 0, "Climbing");
            Go("Climb", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Climbing");
            Go("ClimbIdle", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Climbing");
            Go("Climb", "ClimbIdle").AddCondition(AnimatorConditionMode.Less, 0.1f, "ClimbSpeed");
            Go("ClimbIdle", "Climb").AddCondition(AnimatorConditionMode.Greater, 0.1f, "ClimbSpeed");

            var tIW = Go("Idle", "Walk"); tIW.AddCondition(AnimatorConditionMode.Greater, 0.1f, "Speed"); tIW.AddCondition(AnimatorConditionMode.IfNot, 0, "Crouching");
            Go("Walk", "Idle").AddCondition(AnimatorConditionMode.Less, 0.1f, "Speed");
            Go("Walk", "Run").AddCondition(AnimatorConditionMode.Greater, 4f, "Speed");
            Go("Run", "Walk").AddCondition(AnimatorConditionMode.Less, 4f, "Speed");
            Go("Run", "Idle").AddCondition(AnimatorConditionMode.Less, 0.1f, "Speed");
            Go("Jump", "Fall", true);
            Go("Fall", "Land").AddCondition(AnimatorConditionMode.If, 0, "Grounded");
            Go("Land", "Idle", true);
            Go("Attack", "Idle", true);
            Go("Hit", "Idle", true);
            Go("PickUp", "Idle", true);

            // chop / mine: bool true = keep swinging (loops), false = back to Idle. Only from standing still.
            var tc = Go("Idle", "Chop"); tc.AddCondition(AnimatorConditionMode.If, 0, "Chopping"); tc.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            var tm = Go("Idle", "Mine"); tm.AddCondition(AnimatorConditionMode.If, 0, "Mining"); tm.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            Go("Chop", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Chopping");
            Go("Mine", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Mining");

            // ledge: LedgeHang = true grabs the ledge (from the normal states), trigger LedgeClimb pulls up, LedgeHang = false lets go
            foreach (var f in new[] { "Idle", "Walk", "Run", "Jump", "Fall", "Land" }) { var tl = Go(f, "LedgeHang"); tl.AddCondition(AnimatorConditionMode.If, 0, "LedgeHang"); tl.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); }
            Go("LedgeHang", "LedgeClimb").AddCondition(AnimatorConditionMode.If, 0, "LedgeClimb");
            Go("LedgeHang", "Fall").AddCondition(AnimatorConditionMode.IfNot, 0, "LedgeHang");
            Go("LedgeClimb", "Idle", true);

            // crouch: Crouching (bool) = held Ctrl on the ground. Still = Crouch, moving = CrouchWalk
            var tIC = Go("Idle", "Crouch"); tIC.AddCondition(AnimatorConditionMode.If, 0, "Crouching"); tIC.AddCondition(AnimatorConditionMode.Less, 0.1f, "Speed"); tIC.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            var tICW = Go("Idle", "CrouchWalk"); tICW.AddCondition(AnimatorConditionMode.If, 0, "Crouching"); tICW.AddCondition(AnimatorConditionMode.Greater, 0.1f, "Speed"); tICW.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            foreach (var f in new[] { "Walk", "Run" }) { var tw = Go(f, "CrouchWalk"); tw.AddCondition(AnimatorConditionMode.If, 0, "Crouching"); tw.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned"); }
            Go("Crouch", "CrouchWalk").AddCondition(AnimatorConditionMode.Greater, 0.1f, "Speed");
            Go("CrouchWalk", "Crouch").AddCondition(AnimatorConditionMode.Less, 0.1f, "Speed");
            Go("Crouch", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Crouching");
            var tCWw = Go("CrouchWalk", "Walk"); tCWw.AddCondition(AnimatorConditionMode.IfNot, 0, "Crouching"); tCWw.AddCondition(AnimatorConditionMode.Greater, 0.1f, "Speed");
            var tCWi = Go("CrouchWalk", "Idle"); tCWi.AddCondition(AnimatorConditionMode.IfNot, 0, "Crouching"); tCWi.AddCondition(AnimatorConditionMode.Less, 0.1f, "Speed");

            // roll: trigger Roll (Alt). Afterwards back to Crouch if Ctrl is held or there is no room to stand up, else Idle
            var tR = Any("Roll"); tR.AddCondition(AnimatorConditionMode.If, 0, "Roll"); tR.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); tR.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            Go("Roll", "Crouch", true).AddCondition(AnimatorConditionMode.If, 0, "Crouching");
            Go("Roll", "Idle", true);

            // drink: trigger Drink (potion). Plays once, then Idle
            var tD = Any("Drink"); tD.AddCondition(AnimatorConditionMode.If, 0, "Drink"); tD.AddCondition(AnimatorConditionMode.IfNot, 0, "Dead"); tD.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned"); tD.AddCondition(AnimatorConditionMode.IfNot, 0, "Blocking");
            Go("Drink", "Idle", true);
            // EnterDoor has no transitions: DoorEnterDriver plays it by hand (turns the Animator off while it runs)

            // after Death the body fades away (and stays gone)
            Go("Death", "DeathFade", true);

            // shield: Blocking = true raises it, false lowers it; ShieldHit trigger = hit while blocking
            foreach (var f in new[] { "Idle", "Walk", "Run", "Land" }) { var tb = Go(f, "ShieldRaise"); tb.AddCondition(AnimatorConditionMode.If, 0, "Blocking"); tb.AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned"); }
            Go("ShieldRaise", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Blocking");
            Go("ShieldRaise", "ShieldHold", true);
            Go("ShieldHold", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Blocking");
            Go("ShieldRaise", "ShieldHit").AddCondition(AnimatorConditionMode.If, 0, "ShieldHit");
            Go("ShieldHold", "ShieldHit").AddCondition(AnimatorConditionMode.If, 0, "ShieldHit");
            Go("ShieldHit", "Idle").AddCondition(AnimatorConditionMode.IfNot, 0, "Blocking");
            Go("ShieldHit", "ShieldHold", true);

            // stun: trigger Stun starts it, Stunned (bool) keeps the loop going, Stunned = false ends it
            Go("StunIntro", "StunRecover").AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            Go("StunIntro", "StunLoop", true);
            Go("StunLoop", "StunRecover").AddCondition(AnimatorConditionMode.IfNot, 0, "Stunned");
            Go("StunRecover", "Idle", true);

            // 5) material + prefab
            Material mat = null;
            var shader = Shader.Find(shaderMaterial);
            if (shader != null)
            {
                string matPath = outFolder + "/PlayerPaletteSwap.mat";
                mat = AssetDatabase.LoadAssetAtPath<Material>(matPath);
                if (mat == null) { mat = new Material(shader); AssetDatabase.CreateAsset(mat, matPath); }
            }
            else Debug.LogWarning("Shader " + shaderMaterial + " not found - layers use the default sprite material (no colour swap).");

            var root = new GameObject("Player");
            var animator = root.AddComponent<Animator>();
            animator.runtimeAnimatorController = ctrl;
            var sync = root.AddComponent<PlayerLayerSync>();
            var slots = new List<PlayerLayerSync.Slot>();
            for (int i = 0; i < DrawOrder.Length; i++)
            {
                string layer = DrawOrder[i];
                var go = new GameObject(layer);
                go.transform.SetParent(root.transform, false);
                var sr = go.AddComponent<SpriteRenderer>();
                sr.sortingOrder = i;
                if (mat != null) sr.sharedMaterial = mat;
                slots.Add(new PlayerLayerSync.Slot
                {
                    name = layer, renderer = sr, set = sets[layer],
                    gender = layer.EndsWith("_F") ? PlayerLayerSync.Gender.Female : layer.EndsWith("_M") ? PlayerLayerSync.Gender.Male : PlayerLayerSync.Gender.Both
                });
            }
            sync.slots = slots.ToArray();
            sync.animationNames = Anims.Select(a => a.name).ToArray();
            root.AddComponent<PlayerPalette>();
            string prefabPath = outFolder + "/Player.prefab";
            PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
            DestroyImmediate(root);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log("DeepVain player built: " + prefabPath);
            Selection.activeObject = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
        }
    }
}
#endif
