using System.Collections;
using UnityEngine;
using DeepVain.Player;

/// <summary>
/// Plays the "LedgeUp" animation (stand at the wall -> crouch -> jump and grab -> hang -> pull up -> stand on top)
/// and moves the player smoothly from the start position to the top of the ledge.
///
/// The sprites are drawn IN PLACE (the pelvis never moves inside the picture). All the movement comes from here, so the
/// climb is exactly as high as the ledge and as far as the target, no matter what scale the player has.
/// Put this on the same object as PlayerMovement. PlayerMovement calls Play(...).
/// </summary>
[DisallowMultipleComponent]
public class LedgeClimbDriver : MonoBehaviour
{
    [Tooltip("1 = as drawn (about 1.1 seconds). 1.3 = faster, 0.8 = slower.")]
    public float playbackSpeed = 1f;
    [Tooltip("Writes the player scale to the Console the first time a climb starts.")]
    public bool logScale = true;
    [Header("Ledges higher than one tile")]
    [Tooltip("Frame (of the 23) shown while the player jumps up to the edge: arms reaching up. 6 = the reach.")]
    public int riseFrame = 6;
    [Tooltip("Seconds for the jump up to a ledge exactly as high as the drawn climb.")]
    public float riseBaseTime = 0.16f;
    [Tooltip("Extra seconds per extra tile of height.")]
    public float risePerUnit = 0.14f;

    // ---- generated by the sprite script (LedgeUp): duration of every frame in ms, and the pelvis path in art pixels
    //      (x forward, y up, relative to the first frame). 40 art pixels up = one tile.
    static readonly int[] Ms = { 35, 35, 40, 40, 40, 40, 35, 35, 55, 55, 50, 50, 45, 45, 45, 45, 50, 50, 50, 50, 45, 45, 110 };
    static readonly Vector2[] Path =
    {
        new Vector2(0.00f, 0.00f),
        new Vector2(-0.25f, -1.75f),
        new Vector2(-0.50f, -3.50f),
        new Vector2(-0.25f, -0.25f),
        new Vector2(0.00f, 3.00f),
        new Vector2(0.00f, 4.50f),
        new Vector2(0.00f, 6.00f),
        new Vector2(0.00f, 5.50f),
        new Vector2(0.00f, 5.00f),
        new Vector2(0.25f, 6.50f),
        new Vector2(0.50f, 8.00f),
        new Vector2(1.00f, 10.50f),
        new Vector2(1.50f, 13.00f),
        new Vector2(2.25f, 14.75f),
        new Vector2(3.00f, 16.50f),
        new Vector2(4.50f, 18.75f),
        new Vector2(6.00f, 21.00f),
        new Vector2(7.75f, 24.50f),
        new Vector2(9.50f, 28.00f),
        new Vector2(11.25f, 31.50f),
        new Vector2(13.00f, 35.00f),
        new Vector2(14.50f, 37.50f),
        new Vector2(16.00f, 40.00f)
    };
    const string AnimName = "LedgeUp";

    PlayerLayerSync sync;
    Animator animator;
    float[] centre;
    float totalMs;
    bool logged;

    void Awake()
    {
        sync = GetComponentInChildren<PlayerLayerSync>();
        animator = GetComponentInChildren<Animator>();
        centre = new float[Ms.Length];
        float t = 0f;
        for (int i = 0; i < Ms.Length; i++) { centre[i] = t + Ms[i] * 0.5f; t += Ms[i]; }
        totalMs = t;
    }

    int FindAnimIndex()
    {
        if (sync == null || sync.animationNames == null) return -1;
        for (int i = 0; i < sync.animationNames.Length; i++)
            if (sync.animationNames[i] == AnimName) return i;
        return -1;
    }

    /// <summary>True when the LedgeUp animation exists in the built player (run DeepVain > Player Setup > Build).</summary>
    public bool Ready { get { return sync != null && FindAnimIndex() >= 0; } }

    float UnitsPerArtPixel()
    {
        if (sync == null || sync.slots == null) return 0f;
        foreach (var s in sync.slots)
            if (s != null && s.renderer != null && s.renderer.sprite != null)
                return Mathf.Abs(s.renderer.transform.lossyScale.y) / s.renderer.sprite.pixelsPerUnit;
        return 0f;
    }

    int FrameAt(float tm)
    {
        float t = 0f;
        for (int i = 0; i < Ms.Length; i++) { t += Ms[i]; if (tm < t) return i; }
        return Ms.Length - 1;
    }

    Vector2 Sample(float tm)
    {
        int n = Path.Length;
        if (tm <= centre[0]) return Path[0];
        if (tm >= centre[n - 1]) return Path[n - 1];
        int k = 0;
        while (k < n - 2 && centre[k + 1] <= tm) k++;
        float s = (tm - centre[k]) / (centre[k + 1] - centre[k]);
        Vector2 p0 = Path[Mathf.Max(k - 1, 0)], p1 = Path[k], p2 = Path[k + 1], p3 = Path[Mathf.Min(k + 2, n - 1)];
        return 0.5f * ((2f * p1) + (-p0 + p2) * s + (2f * p0 - 5f * p1 + 4f * p2 - p3) * s * s + (-p0 + 3f * p1 - 3f * p2 + p3) * s * s * s);
    }

    /// <summary>Call from a coroutine. start / target are Rigidbody2D positions. ledgeHeight is only used for the scale check.</summary>
    public IEnumerator Play(Rigidbody2D rb, Vector2 start, Vector2 target, float ledgeHeight, bool fromAir = false)
    {
        int idx = FindAnimIndex();
        if (idx < 0) yield break;

        if (logScale && !logged)
        {
            logged = true;
            float u = UnitsPerArtPixel();
            float drawn = Path[Path.Length - 1].y * u;
            Debug.Log("[LedgeClimbDriver] 1 sprite pixel = " + u.ToString("0.0000") + " units. The player is 40 pixels = " + (40f * u).ToString("0.00")
                + " units tall. The climb is drawn " + drawn.ToString("0.00") + " units high; the ledge is " + ledgeHeight.ToString("0.00") + " units high.");
            if (u > 0f && Mathf.Abs(drawn - ledgeHeight) > 0.08f * ledgeHeight)
                Debug.LogWarning("[LedgeClimbDriver] The player is not 1 tile tall (40 pixels should equal the ledge height). Change Pixels Per Unit in Player Setup, or the scale of the player, until the two numbers match.");
        }

        float speed = Mathf.Max(0.1f, playbackSpeed);
        Vector2 end = Path[Path.Length - 1];

        // Ledges higher than the drawn climb: crouch as drawn, JUMP up the extra height (arms reaching), then pull up as drawn.
        float pxUnit = UnitsPerArtPixel();
        float natural = pxUnit > 0f ? end.y * pxUnit : ledgeHeight;
        float height = target.y - start.y;
        float extra = height > natural * 1.04f ? height - natural : 0f;
        int rf = Mathf.Clamp(riseFrame, 1, Ms.Length - 1);
        float riseStartMs = 0f; for (int i = 0; i < rf; i++) riseStartMs += Ms[i];
        float rise = extra > 0f ? riseBaseTime + risePerUnit * extra : 0f;       // animation seconds
        // from the air the crouch is skipped: the player is already reaching for the edge
        float ta0 = fromAir ? riseStartMs / 1000f : 0f;
        Vector2 p0 = fromAir ? Sample(riseStartMs) : Vector2.zero;
        float kx = (target.x - start.x) / (end.x - p0.x);
        float ky = (height - extra) / (end.y - p0.y);
        float total = (totalMs / 1000f + rise - ta0) / speed;

        if (animator != null) animator.enabled = false;      // this script chooses the frames while it plays
        sync.animId = idx;

        float t = 0f;
        while (t < total)
        {
            float ta = t * speed + ta0;                        // animation seconds (rise included)
            float tm, up = 0f; int frame;
            if (extra <= 0f || ta * 1000f < riseStartMs) { tm = ta * 1000f; frame = FrameAt(tm); }
            else if (ta < riseStartMs / 1000f + rise)
            {
                float s = (ta - riseStartMs / 1000f) / rise;
                tm = riseStartMs; up = extra * (1f - (1f - s) * (1f - s)); frame = rf;   // fast at first, slows at the top
            }
            else { tm = (ta - rise) * 1000f; up = extra; frame = FrameAt(tm); }
            tm = Mathf.Min(tm, totalMs - 0.01f);
            sync.frame = frame;
            Vector2 p = Sample(tm) - p0;
            rb.MovePosition(new Vector2(start.x + p.x * kx, start.y + p.y * ky + up));
            t += Time.fixedDeltaTime;
            yield return new WaitForFixedUpdate();
        }
        sync.frame = Ms.Length - 1;
        rb.MovePosition(target);
        yield return new WaitForFixedUpdate();
    }

    /// <summary>Gives the Animator control back. PlayerMovement calls this when the climb is over or cancelled.</summary>
    public void Stop()
    {
        if (animator != null) animator.enabled = true;
    }
}
